apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app: simple-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
        - name: simple-api
          image: maha997/simple-api:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: storage # ✅ This must match `volumes.name`
              mountPath: /app/data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: storage # ✅ This name must match `volumeMounts.name`
          persistentVolumeClaim:
            claimName: simple-api-pvc # ✅ This must match the PVC name
