apiVersion: v1
kind: PersistentVolumeClaim # ✅ Correct capitalization!
metadata:
  name: simple-api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: manual
